import type { ResourceArticle } from './data.ts';

// Editorial translations of the three starter articles. References remain canonical.
type ArticleText = Pick<ResourceArticle, 'title' | 'category' | 'readTime' | 'summary' | 'content'>;
export const articleTranslations: Record<string, ArticleText[]> = {
  de: [
    {title:'Die Gute Nachricht in vier Kapiteln: Schöpfung, Sündenfall, Erlösung, Erneuerung',category:'Grundlagen',readTime:'4 Min. Lesezeit',summary:'Die grosse Geschichte der Menschheit und warum Jesus uns den Weg zu Gott öffnet.',content:['1. Schöpfung: Gott schuf eine schöne, geordnete Welt und Menschen mit Würde, die in Gemeinschaft mit ihm leben sollten.','2. Sündenfall: Wir Menschen wandten uns von Gott ab. Dadurch zerbrachen Beziehungen, und Schuld und Leid kamen in die Welt.','3. Erlösung: Wir können uns nicht selbst durch gute Taten oder Rituale retten. Darum kam Jesus Christus, lebte ohne Sünde und starb für uns am Kreuz.','4. Erneuerung: Jesus ist leibhaftig auferstanden. Wer ihm vertraut, empfängt Vergebung, wird Gottes Kind und darf auf eine erneuerte Schöpfung hoffen.']},
    {title:'Aus Gnade gerettet, nicht durch Werke',category:'Glaubenslehre',readTime:'3 Min. Lesezeit',summary:'Die Gute Nachricht: Gottes Annahme ist ein Geschenk und kann nicht verdient werden.',content:['Viele Weltanschauungen verlangen, dass Menschen sich Gottes Gunst durch Regeln, Rituale oder eigene Leistung verdienen.','Die christliche Botschaft lautet dagegen: Gott selbst kam zu uns, um uns zu retten.','Epheser 2,8–9 sagt, dass wir aus Gnade durch Glauben gerettet sind. Das ist Gottes Geschenk, nicht das Ergebnis unserer Werke.','Gute Taten sind die Frucht der Rettung, nicht ihre Voraussetzung.']},
    {title:'Glaubenswegweiser für Zugewanderte in der Schweiz',category:'Gemeinschaft',readTime:'5 Min. Lesezeit',summary:'Praktische Hinweise, um als neu zugezogene Person Gemeinschaft und eine Kirche zu finden.',content:['Ein Umzug in die Schweiz kann herausfordernd sein: mehrere Landessprachen, unterschiedliche Kantone und neue soziale Gewohnheiten.','Christliche Gemeinden in Zürich, Genf, Basel, Bern und im Tessin heissen Menschen aus vielen Ländern willkommen.','Ob du Deutsch, Französisch, Italienisch, Spanisch, Portugiesisch, Albanisch, Serbisch oder Filipino sprichst: Suche eine Gemeinde, in der du Anschluss findest.','Nutze das Gemeindeverzeichnis, um eine Kirche oder Kleingruppe in deiner Nähe zu finden.']},
  ],
  fr: [
    {title:'La Bonne Nouvelle en quatre chapitres : création, chute, rédemption, restauration',category:'Fondements',readTime:'4 min de lecture',summary:'La grande histoire de l’humanité et la manière dont Jésus nous ouvre le chemin vers Dieu.',content:['1. Création : Dieu a créé un monde beau et ordonné et des êtres humains dignes de vivre en relation avec lui.','2. Chute : l’humanité s’est détournée de Dieu. Les relations se sont brisées, et la culpabilité et la souffrance sont entrées dans le monde.','3. Rédemption : ni nos efforts ni nos rites ne peuvent nous sauver. Jésus-Christ est venu, a vécu sans péché et est mort pour nous sur la croix.','4. Restauration : Jésus est ressuscité corporellement. Quiconque lui fait confiance reçoit le pardon, devient enfant de Dieu et espère une création renouvelée.']},
    {title:'Sauvés par la grâce, et non par les œuvres',category:'Théologie',readTime:'3 min de lecture',summary:'La Bonne Nouvelle : l’accueil de Dieu est un don, pas une récompense à gagner.',content:['De nombreuses visions du monde demandent de mériter la faveur divine par des règles, des rites ou des performances.','La foi chrétienne annonce au contraire que Dieu est venu lui-même nous secourir.','Éphésiens 2.8–9 enseigne que nous sommes sauvés par la grâce, au moyen de la foi. C’est un don de Dieu, non le résultat de nos œuvres.','Les bonnes œuvres sont le fruit du salut, jamais sa condition.']},
    {title:'Guide de foi pour les personnes migrantes en Suisse',category:'Communauté',readTime:'5 min de lecture',summary:'Des pistes pratiques pour trouver une Église et des relations après une arrivée en Suisse.',content:['S’installer en Suisse peut être difficile : plusieurs langues nationales, des cantons différents et de nouveaux codes sociaux.','Des communautés chrétiennes à Zurich, Genève, Bâle, Berne et au Tessin accueillent des personnes de nombreux pays.','Quelle que soit votre langue, cherchez une communauté locale ou internationale où vous pourrez tisser des liens.','Consultez l’annuaire des Églises pour trouver une assemblée ou un petit groupe près de chez vous.']},
  ],
  it: [
    {title:'La Buona Notizia in quattro capitoli: creazione, caduta, redenzione, rinnovamento',category:'Fondamenti',readTime:'4 min di lettura',summary:'La grande storia dell’umanità e il modo in cui Gesù ci riporta a Dio.',content:['1. Creazione: Dio ha creato un mondo bello e ordinato e persone dotate di dignità, chiamate a vivere in comunione con lui.','2. Caduta: l’umanità si è allontanata da Dio. Le relazioni si sono spezzate e nel mondo sono entrate colpa e sofferenza.','3. Redenzione: non possiamo salvarci con opere buone o riti. Gesù Cristo è venuto, ha vissuto senza peccato ed è morto per noi sulla croce.','4. Rinnovamento: Gesù è risorto corporalmente. Chi si affida a lui riceve perdono, diventa figlio di Dio e attende una creazione rinnovata.']},
    {title:'Salvati per grazia, non per opere',category:'Teologia',readTime:'3 min di lettura',summary:'La Buona Notizia: l’accoglienza di Dio è un dono, non un premio da guadagnare.',content:['Molte visioni del mondo chiedono di meritare il favore divino attraverso regole, riti o risultati personali.','Il messaggio cristiano annuncia invece che Dio stesso è venuto a soccorrerci.','Efesini 2:8–9 insegna che siamo salvati per grazia mediante la fede. È un dono di Dio, non il risultato delle nostre opere.','Le buone opere sono il frutto della salvezza, non la sua condizione.']},
    {title:'Guida di fede per migranti e nuovi arrivati in Svizzera',category:'Comunità',readTime:'5 min di lettura',summary:'Consigli pratici per trovare una chiesa e nuove relazioni in Svizzera.',content:['Trasferirsi in Svizzera può essere impegnativo: più lingue nazionali, cantoni diversi e nuove abitudini sociali.','Le comunità cristiane di Zurigo, Ginevra, Basilea, Berna e del Ticino accolgono persone di molti paesi.','Qualunque sia la tua lingua, cerca una comunità locale o internazionale in cui sentirti a casa.','Consulta l’elenco delle chiese per trovare una comunità o un piccolo gruppo vicino a te.']},
  ],
  rm: [
    {title:'La Buna Novitad en quatter chapitels: creaziun, crudada, spendrament, renovaziun',category:'Fundaments',readTime:'4 minutas da leger',summary:'La gronda istorgia da l’umanitad e co che Jesus ans avra la via tar Dieu.',content:['1. Creaziun: Dieu ha creà in mund bel ed ordinà e carstgauns cun dignitad per viver en cuminanza cun el.','2. Crudada: l’umanitad è sa distanziada da Dieu. Las relaziuns èn sa ruttas, e culpa e suffrientscha èn entradas en il mund.','3. Spendrament: nus na pudain betg ans salvar tras bunas ovras u rituals. Jesus Cristus è vegnì, ha vivì senza putgà ed è mort per nus vi da la crusch.','4. Renovaziun: Jesus è levà en vita cun ses corp. Tgi che sa fida dad el survegn perdun, daventa uffant da Dieu e spetga in mund renovà.']},
    {title:'Salvads tras grazia, betg tras ovras',category:'Teologia',readTime:'3 minutas da leger',summary:'La Buna Novitad: l’acceptanza da Dieu è in regal, betg ina paja.',content:['Blers puncts da vista pretendan che nus meritian il bainvulair divin tras reglas, rituals u prestaziuns.','La cretta cristiana annunzia percunter che Dieu sez è vegnì per ans gidar.','Efesers 2:8–9 mussa che nus essan salvads tras grazia e tras la cretta. Quai è in regal da Dieu, betg il resultat da nossas ovras.','Bunas ovras èn il fritg dal spendrament, betg sia premissa.']},
    {title:'Guida da cretta per persunas immigradas en Svizra',category:'Cuminanza',readTime:'5 minutas da leger',summary:'Tips pratics per chattar ina baselgia e cuminanza en Svizra.',content:['Viver en Svizra po esser ina sfida: pliras linguas naziunalas, chantuns differents e novas isanzas socialas.','Cuminanzas cristianas a Turitg, Genevra, Basilea, Berna ed en il Tessin beneventan persunas da blers pajais.','Independentamain da tia lingua, tschertga ina cuminanza locala u internaziunala nua che ti pos far novas amicizias.','Dovra il register da baselgias per chattar ina baselgia u ina gruppa pitschna en tia vischinanza.']},
  ],
  sq: [
    {title:'Lajmi i Mirë në katër kapituj: Krijimi, Rënia, Shpengimi, Ripërtëritja',category:'Themelet',readTime:'4 min lexim',summary:'Historia e madhe e njerëzimit dhe si na hap Jezusi rrugën drejt Perëndisë.',content:['1. Krijimi: Perëndia krijoi një botë të bukur dhe njerëz me dinjitet për të jetuar në bashkësi me të.','2. Rënia: njerëzimi u largua nga Perëndia. Marrëdhëniet u prishën dhe faji e vuajtja hynë në botë.','3. Shpengimi: veprat e mira dhe ritualet nuk na shpëtojnë dot. Jezu Krishti erdhi, jetoi pa mëkat dhe vdiq për ne në kryq.','4. Ripërtëritja: Jezusi u ringjall trupërisht. Kush beson tek ai merr falje, bëhet fëmijë i Perëndisë dhe pret një krijim të ripërtërirë.']},
    {title:'Të shpëtuar nga hiri, jo nga veprat',category:'Teologji',readTime:'3 min lexim',summary:'Lajmi i Mirë: pranimi nga Perëndia është dhuratë, jo shpërblim që fitohet.',content:['Shumë pikëpamje kërkojnë që njeriu ta fitojë miratimin hyjnor me rregulla, rituale ose arritje.','Mesazhi i krishterë shpall se vetë Perëndia erdhi për të na shpëtuar.','Efesianëve 2:8–9 thotë se shpëtohemi me anë të hirit, nëpërmjet besimit. Kjo është dhuratë e Perëndisë, jo rezultat i veprave tona.','Veprat e mira janë fryt i shpëtimit, jo kusht i tij.']},
    {title:'Udhëzues besimi për migrantët në Zvicër',category:'Bashkësi',readTime:'5 min lexim',summary:'Këshilla praktike për të gjetur kishë dhe miqësi pas ardhjes në Zvicër.',content:['Shpërngulja në Zvicër mund të jetë e vështirë: disa gjuhë kombëtare, kantone të ndryshme dhe zakone të reja shoqërore.','Bashkësitë e krishtera në Cyrih, Gjenevë, Bazel, Bernë dhe Tiçino mirëpresin njerëz nga shumë vende.','Cilado qoftë gjuha jote, kërko një bashkësi vendase ose ndërkombëtare ku mund të krijosh miqësi.','Përdor listën e kishave për të gjetur një kishë ose grup të vogël pranë teje.']},
  ],
  pt: [
    {title:'A Boa Notícia em quatro capítulos: criação, queda, redenção, restauração',category:'Fundamentos',readTime:'4 min de leitura',summary:'A grande história da humanidade e como Jesus nos abre o caminho para Deus.',content:['1. Criação: Deus criou um mundo belo e ordenado e pessoas com dignidade para viverem em comunhão com ele.','2. Queda: a humanidade afastou-se de Deus. As relações quebraram-se, e a culpa e o sofrimento entraram no mundo.','3. Redenção: não conseguimos salvar-nos por boas obras ou rituais. Jesus Cristo veio, viveu sem pecado e morreu por nós na cruz.','4. Restauração: Jesus ressuscitou fisicamente. Quem confia nele recebe perdão, torna-se filho de Deus e espera uma criação renovada.']},
    {title:'Salvos pela graça, não pelas obras',category:'Teologia',readTime:'3 min de leitura',summary:'A Boa Notícia: a aceitação de Deus é uma dádiva, não algo que se conquista.',content:['Muitas visões do mundo exigem que as pessoas mereçam o favor divino por regras, rituais ou desempenho.','A mensagem cristã anuncia, pelo contrário, que o próprio Deus veio salvar-nos.','Efésios 2:8–9 ensina que somos salvos pela graça, mediante a fé. É uma dádiva de Deus, não o resultado das nossas obras.','As boas obras são o fruto da salvação, nunca a sua condição.']},
    {title:'Guia de fé para migrantes na Suíça',category:'Comunidade',readTime:'5 min de leitura',summary:'Conselhos práticos para encontrar uma igreja e novas amizades na Suíça.',content:['Mudar-se para a Suíça pode ser difícil: várias línguas nacionais, cantões diferentes e novos hábitos sociais.','Comunidades cristãs em Zurique, Genebra, Basileia, Berna e no Ticino acolhem pessoas de muitos países.','Seja qual for a sua língua, procure uma comunidade local ou internacional onde possa criar laços.','Consulte o diretório de igrejas para encontrar uma igreja ou pequeno grupo perto de si.']},
  ],
  es: [
    {title:'La Buena Noticia en cuatro capítulos: creación, caída, redención, restauración',category:'Fundamentos',readTime:'4 min de lectura',summary:'La gran historia de la humanidad y cómo Jesús nos abre el camino hacia Dios.',content:['1. Creación: Dios creó un mundo hermoso y ordenado y personas con dignidad para vivir en comunión con él.','2. Caída: la humanidad se alejó de Dios. Las relaciones se rompieron, y la culpa y el sufrimiento entraron en el mundo.','3. Redención: las buenas obras y los ritos no pueden salvarnos. Jesucristo vino, vivió sin pecado y murió por nosotros en la cruz.','4. Restauración: Jesús resucitó corporalmente. Quien confía en él recibe perdón, llega a ser hijo de Dios y espera una creación renovada.']},
    {title:'Salvos por gracia, no por obras',category:'Teología',readTime:'3 min de lectura',summary:'La Buena Noticia: la aceptación de Dios es un regalo, no algo que se gana.',content:['Muchas cosmovisiones exigen que las personas merezcan el favor divino mediante normas, ritos o logros.','El mensaje cristiano anuncia, en cambio, que Dios mismo vino a rescatarnos.','Efesios 2:8–9 enseña que somos salvos por gracia mediante la fe. Es un regalo de Dios, no el resultado de nuestras obras.','Las buenas obras son el fruto de la salvación, nunca su condición.']},
    {title:'Guía de fe para migrantes en Suiza',category:'Comunidad',readTime:'5 min de lectura',summary:'Consejos prácticos para encontrar una iglesia y nuevas amistades en Suiza.',content:['Mudarse a Suiza puede ser difícil: varias lenguas nacionales, distintos cantones y nuevas costumbres sociales.','Las comunidades cristianas de Zúrich, Ginebra, Basilea, Berna y el Tesino reciben a personas de muchos países.','Sea cual sea tu idioma, busca una comunidad local o internacional donde puedas crear vínculos.','Consulta el directorio de iglesias para encontrar una iglesia o grupo pequeño cerca de ti.']},
  ],
  sr: [
    {title:'Dobra vest u četiri poglavlja: stvaranje, pad, otkupljenje, obnova',category:'Osnove',readTime:'4 min čitanja',summary:'Velika priča čovečanstva i kako nam Isus otvara put ka Bogu.',content:['1. Stvaranje: Bog je stvorio lep i uređen svet i ljude s dostojanstvom da žive u zajedništvu s njim.','2. Pad: ljudi su se udaljili od Boga. Odnosi su narušeni, a krivica i patnja ušle su u svet.','3. Otkupljenje: dobra dela i obredi ne mogu nas spasiti. Isus Hristos je došao, živeo bez greha i umro za nas na krstu.','4. Obnova: Isus je telesno vaskrsao. Ko mu veruje prima oproštaj, postaje Božje dete i nada se obnovljenom svetu.']},
    {title:'Spaseni milošću, a ne delima',category:'Teologija',readTime:'3 min čitanja',summary:'Dobra vest: Božje prihvatanje je dar, a ne nagrada koju zaslužujemo.',content:['Mnogi pogledi na svet traže da se Božja naklonost zasluži pravilima, obredima ili postignućima.','Hrišćanska poruka, naprotiv, kaže da je sam Bog došao da nas spase.','Efescima 2:8–9 uči da smo spaseni milošću kroz veru. To je Božji dar, a ne rezultat naših dela.','Dobra dela su plod spasenja, nikada njegov uslov.']},
    {title:'Vodič kroz veru za migrante u Švajcarskoj',category:'Zajednica',readTime:'5 min čitanja',summary:'Praktični saveti za pronalaženje crkve i prijatelja u Švajcarskoj.',content:['Preseljenje u Švajcarsku može biti izazovno: više nacionalnih jezika, različiti kantoni i nove društvene navike.','Hrišćanske zajednice u Cirihu, Ženevi, Bazelu, Bernu i Tičinu dočekuju ljude iz mnogih zemalja.','Bez obzira na jezik kojim govoriš, potraži lokalnu ili međunarodnu zajednicu u kojoj možeš steći prijatelje.','Koristi imenik crkava da pronađeš crkvu ili malu grupu u svojoj blizini.']},
  ],
  fil: [
    {title:'Ang Mabuting Balita sa apat na yugto: paglikha, pagkabagsak, pagtubos, pagpapanibago',category:'Mga Pundasyon',readTime:'4 minutong basa',summary:'Ang dakilang kuwento ng sangkatauhan at kung paano tayo inilalapit ni Jesus sa Diyos.',content:['1. Paglikha: lumikha ang Diyos ng maganda at maayos na mundo at ng mga taong may dignidad upang makipag-ugnayan sa kaniya.','2. Pagkabagsak: tumalikod ang sangkatauhan sa Diyos. Nasira ang mga ugnayan at pumasok sa mundo ang kasalanan at pagdurusa.','3. Pagtubos: hindi natin maililigtas ang sarili sa mabubuting gawa o ritwal. Dumating si Jesu-Cristo, namuhay nang walang kasalanan, at namatay para sa atin sa krus.','4. Pagpapanibago: muling nabuhay si Jesus sa katawan. Ang nagtitiwala sa kaniya ay tumatanggap ng kapatawaran, nagiging anak ng Diyos, at umaasa sa bagong sangnilikha.']},
    {title:'Naligtas sa biyaya, hindi sa gawa',category:'Teolohiya',readTime:'3 minutong basa',summary:'Ang Mabuting Balita: regalo ang pagtanggap ng Diyos, hindi gantimpalang pinaghihirapan.',content:['Maraming pananaw ang nagsasabing kailangang paghirapan ang pabor ng Diyos sa pamamagitan ng tuntunin, ritwal, o sariling tagumpay.','Ipinahahayag naman ng pananampalatayang Kristiyano na ang Diyos mismo ang dumating upang iligtas tayo.','Ayon sa Efeso 2:8–9, naligtas tayo sa biyaya sa pamamagitan ng pananampalataya. Regalo ito ng Diyos, hindi bunga ng ating mga gawa.','Ang mabubuting gawa ay bunga ng kaligtasan, hindi kondisyon nito.']},
    {title:'Gabay sa pananampalataya para sa mga migrante sa Switzerland',category:'Komunidad',readTime:'5 minutong basa',summary:'Praktikal na payo sa paghahanap ng simbahan at kaibigan sa Switzerland.',content:['Maaaring mahirap lumipat sa Switzerland dahil sa iba’t ibang pambansang wika, canton, at kaugaliang panlipunan.','Tumatanggap ng mga tao mula sa maraming bansa ang mga Kristiyanong komunidad sa Zurich, Geneva, Basel, Bern, at Ticino.','Anuman ang wikang ginagamit mo, humanap ng lokal o internasyonal na komunidad na maaari mong makasama.','Gamitin ang direktoryo ng mga simbahan upang makahanap ng simbahan o maliit na grupo malapit sa iyo.']},
  ],
};
